#!/bin/bash -e
if [[ ! -f "/home/spark-eead8841-e71b-4c84-b512-c1/tmp/uv/uv_0.6.10_linux_arm64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-eead8841-e71b-4c84-b512-c1/tmp/uv/uv_0.6.10_linux_arm64" "$@"
